configs:
  i18n:
    keys:
      clubContributorAddedTitle: "CLUB.CONTRIBUTOR-ADDED.TITLE"
      clubContributorAddedMessage: "CLUB.CONTRIBUTOR-ADDED.MESSAGE"
      clubMemberAddedTitle: "CLUB.MEMBER-ADDED.TITLE"
      clubMemberAddedMessage: "CLUB.MEMBER-ADDED.MESSAGE"
    supported-locales:
      en: en
      es: es

