configs:
  i18n:
    keys:
      clubsContributorAddedTitle: "CLUBS.CONTRIBUTOR-ADDED.TITLE"
      clubsContributorAddedMessage: "CLUBS.CONTRIBUTOR-ADDED.TITLE"
      clubMemberAddedTitle: "CLUBS.MEMBER-ADDED.TITLE"
      clubMemberAddedMessage: "CLUBS.MEMBER-ADDED.TITLE"
    supported-locales:
      en: en
      es: es

